tls_first_implementation
rabbitmq/rabbitmq-stream-rust-client pull request #155
Opened 2023-01-26 08:47 UTC by DanielePalaia

This first implementation of TLS support includes:

- Integrate the tokio-native-tls library
- Implements an Environment Helper Class "TlsConfiguration" to manage Tls options in Environment
- Implements Tls trusting all hostnames and certificates at the moment (just encryption offered)
- Adding a test on port 5551

2023-02-01 08:09 UTC, wolf4ood requested changes

2023-02-01 08:09 UTC, wolf4ood commented on src/environment.rs
> +}
For the `TlsConfiguration` probably it's better if we do a builder pattern?

Something like this

```rust
pub struct TlsConfigurationBuilder(TlsConfiguration);

impl TlsConfigurationBuilder {

   pub fn trust_everything(mut self, trust_everything: bool)  -> TlsConfigurationBuilder {
        self.0.trust_everything = trust_everything;
        self
    }

    pub fn enable(mut self, enable: bool)  -> TlsConfigurationBuilder {
        self.0.enabled = enabled;
        self
    }


    pub fn hostname_verification_enable(mut self, hostname_verification: bool) -> TlsConfigurationBuilder  {
        self.0.hostname_verification = hostname_verification;
        self
    }

    pub fn build(self) -> TlsConfiguration {
       self.0
    }
}


impl TlsConfiguration {

   pub fn builder() -> TlsConfigurationBulder {
    TlsConfigurationBulder(TlsConfiguration::default())
   }
  
}
```

2023-02-02 18:04 UTC, DanielePalaia commented
Hey @wolf4ood thanks for your review! Addressed the issues!

2023-02-02 19:57 UTC, wolf4ood approved these changes

2023-02-02 19:57 UTC, merged