expose store_offset and query_offset in consumer
rabbitmq/rabbitmq-stream-rust-client pull request #203
Opened 2023-10-13 10:18 UTC by DanielePalaia

This closes https://github.com/rabbitmq/rabbitmq-stream-rust-client/issues/195

Exposes store_offset and query_offset in Consumer struct

2023-10-23 12:22 UTC, Gsantomaggio requested changes
can you add the `Offset Not Found Error` test case? for the query offset in case it does not exist.

2023-10-25 08:25 UTC, Gsantomaggio commented
Can you add a test using a real offset coming form the chunk ?

2023-10-25 09:46 UTC, DanielePalaia commented
Done!

2023-10-25 10:32 UTC, Gsantomaggio approved these changes

2023-10-25 14:30 UTC, wolf4ood approved these changes
LGTM, just a minor nit :)

2023-10-25 14:30 UTC, wolf4ood commented on src/consumer.rs
> +    }
You could make it a little bit shorter like this:

```suggestion
    pub async fn store_offset(&self, offset: u64) -> Result<(), ConsumerStoreOffsetError> {
        if let Some(name) = &self.name {
            self.internal
                .client
                .store_offset(name, self.internal.stream.as_str(), offset)
                .await
                .map(Ok)?
        } else {
            Err(ConsumerStoreOffsetError::NameMissing)
        }
    }
```

same for `query_offset`.

2023-10-25 16:54 UTC, DanielePalaia commented
@Gsantomaggio and @wolf4ood for the review! I also implemented the last suggestion as having more compact code is better!

2023-10-25 16:54 UTC, merged